/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.InterfacesTest;

import InterfacesTest.App;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
