/*
 * This source file was generated by the Gradle 'init' task
 */
package InterfacesTest;

import Views.MainView;
import javafx.application.Application;
import javafx.stage.Stage;
import javafx.geometry.Rectangle2D;
import javafx.stage.Screen;

public class App extends Application{
    @Override
    public void start(Stage stage) {
        MainView mainView = new MainView();
        stage.setScene(mainView.createScene());
        stage.setMaximized(true);
        
        Rectangle2D screenBounds = Screen.getPrimary().getVisualBounds();
        stage.setX(screenBounds.getMinX());
        stage.setY(screenBounds.getMinY());
        stage.setWidth(screenBounds.getWidth());
        stage.setHeight(screenBounds.getHeight());
        
        stage.show();
        
        stage.setScene(mainView.createScene());
        
        stage.setTitle("Mi Aplicación JavaFX");
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
